//Trying a manual rand with a seed
function cyrb128(str) {
    let h1 = 1779033703, h2 = 3144134277,
        h3 = 1013904242, h4 = 2773480762;
    for (let i = 0, k; i < str.length; i++) {
        k = str.charCodeAt(i);
        h1 = h2 ^ Math.imul(h1 ^ k, 597399067);
        h2 = h3 ^ Math.imul(h2 ^ k, 2869860233);
        h3 = h4 ^ Math.imul(h3 ^ k, 951274213);
        h4 = h1 ^ Math.imul(h4 ^ k, 2716044179);
    }
    h1 = Math.imul(h3 ^ (h1 >>> 18), 597399067);
    h2 = Math.imul(h4 ^ (h2 >>> 22), 2869860233);
    h3 = Math.imul(h1 ^ (h3 >>> 17), 951274213);
    h4 = Math.imul(h2 ^ (h4 >>> 19), 2716044179);
    return [(h1^h2^h3^h4)>>>0, (h2^h1)>>>0, (h3^h1)>>>0, (h4^h1)>>>0];
}

function sfc32(a, b, c, d) {
    a >>>= 0; b >>>= 0; c >>>= 0; d >>>= 0; 
    var t = (a + b) | 0;
    a = b ^ b >>> 9;
    b = c + (c << 3) | 0;
    c = (c << 21 | c >>> 11);
    d = d + 1 | 0;
    t = t + d | 0;
    c = c + t | 0;
    return (t >>> 0) / 4294967296;
}

function randOfTheDay(type) {
    const today = new Date();
    const year = today.getFullYear();
    const month = today.getMonth();
    const day = today.getDate();

    // Create cyrb128 state:
    var seed = cyrb128(year+' '+month+' '+day+' '+type);
    // Four 32-bit component hashes provide the seed for sfc32.
    var rand = sfc32(seed[0], seed[1], seed[2], seed[3]);

    return rand;
}

//Capitalize first letter
function capitalizeFirstLetter(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
}

//Compare function
function GetSortOrder(prop) {    
    return function(a, b) {    
        if (a[prop] > b[prop]) {    
            return 1;    
        } else if (a[prop] < b[prop]) {    
            return -1;    
        }    
        return 0;    
    }    
}    

//Missing IDs

var missingItem = [19,104,527,535,578,582,583,610,647,825,826,881,882,907,947,1060,1080,1081];
var missingArmorSet = [158];
var missingWeapon = [1025,1173,1186,1208,1262,1263,1280];
var missingMonster = [46,47];
var missingArmor = [656,657,658,659,660,666,979,1497,1510,1582,1583];
var missingCharm = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233];
var missingSkill = [156,159,160,161];

//Type array

var armorType = ["head","chest","gloves","waist","legs"];

var weaponType = ["great-sword","long-sword","sword-and-shield","dual-blades","hammer","hunting-horn","lance","gunlance","switch-axe","charge-blade","insect-glaive","light-bowgun","heavy-bowgun","bow"];
var weaponName = ["Great sword","Long sword","Sword and shield","Dual blades","Hammer","Hunting horn","Lance","Gunlance","Switch axe","Charge blade","Insect glaive","Light bowgun","Heavy bowgun","Bow"];

var elementName = ["fire","water","ice","thunder","dragon","blast","poison","sleep","paralysis","stun"]

//Img URL

var elementIcon = [
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/mhw-fire-damage.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/mhw-water-elemental-damage.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/mhw-ice-damage.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/mhw-thunder-damage.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/mhw-dragon-damage.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/Blastblight.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/mhw-poison-status-effect.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/sleep-mhw-status-effect.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/paralysis-icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/mhw-stun-status-effect.png"
]

var defaultWeaponURL = [
    "https://assets.mhw-db.com/weapons/great-sword/9876ac2d364c5d15f019e24a8d2c08c4509015af.5e306edb643559c79313457ed6382333.png",
    "https://assets.mhw-db.com/weapons/long-sword/9706a176b1b8dd071ef33376d1c885ccdf545c19.0da7f897eddee1a6a118fbcae6135679.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/placeholder_sword_and_shield.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/placeholder_dual_blade.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/placeholder_hammer.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/placeholder_hunting_horn.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/placeholder_lance.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/placeholder_gunlance.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/placeholder_switch_axe.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/placeholder_charge_blade.png",
    "https://assets.mhw-db.com/weapons/insect-glaive/adeb5e7f179d604903c4b09cf9987f4ab010a632.119abd643a28cc9a87cbd2f74844248f.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/placeholder_light_bowgun.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/placeholder_heavy_bowgun.png",
    "https://assets.mhw-db.com/weapons/bow/20a9cfd9a6a80fa5666c7ab487c7422eff1d9092.05b8f5c24b77309f5fecbd97b9114c61.png"
]

var monsterIconURL = [
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-aptonoth_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-jagras_icon2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-icono_mernos.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-vespoid_icon2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-mosswine_icon2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-apceros_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-kestodon_male_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-noios_icon2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-gajau_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-kelbi_icon2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-raphinos_icon2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-shamos_icon2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-girros_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-hornetaur_icon2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-gastodon_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-barnos_icon2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-great_jagras_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-kulu-ya-ku_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-pukei-pukei_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/MHW-Barroth_Icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-jyuratodus_icon2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-tobi-kadachi_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-anjanath_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-azure_rathalos_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-bazelgeuse_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-behemoth_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-deviljho_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/mhw-diablos_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-black_diablos_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-dodogama_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-great_girros_icon2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-kirin_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-kulve_taroth_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-kushala_daora_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-lavasioth_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-legiana_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-lunastra_icon2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-nergigante_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-odogaron_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-paolumu_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-radobaan_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-rathalos_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-rathian_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-pink_rathian_icon2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-teostra_icon.png",
    "",
    "",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-tzitzi-ya-ku_icon2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-uragaan_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-vaal_hazak_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-xeno'jiiva_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-zorah_magdaros_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-leshen_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/ancient_leshen_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhwi-safi'jiiva_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/stygian_zinogre_icon-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhwi-rajang_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhwi-viper_tobi-kadachi_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhwi-namielle_icon.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhwi-zinogre_icon.png"
]

var monsterImgURL = [
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-aptonoth_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-jagras_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-mernos_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/vespoids.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-mosswine_and_bristly_crake_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-apceros_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-kestodon_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-noios_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-gajau_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-kelbi_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-raphinos_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-shamos_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-girros_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhgen-hornetaur_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-gastodon_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-barnos_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-great_jagras_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-kulu-ya-ku_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-pukei-pukei_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-barroth_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-jyuratodus_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-tobi-kadachi_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-anjanath_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-azure_rathalos_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-bazelgeuse_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-behemoth_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-deviljho_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/mhw-diablos_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-black_diablos_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-dodogama_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-great_girros_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-kirin_render.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-kulve_taroth_render_002_(1).png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-kushala_daora_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-lavasioth_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-legiana_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-lunastra_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-nergigante_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-odogaron_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-paolumu_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-radobaan_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-rathalos_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/rathian_transparent.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-pink_rathian_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-teostra_render_001.png",
    "",
    "",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-tzitzi-ya-ku_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-uragaan_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-vaal_hazak_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-xeno'jiiva_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhw-zorah_magdaros_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/leshen-large-monster-monster-hunter-world-wiki-guide-mhw.jpg",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/ancient_leshen_mhw.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhwi-safi'jiiva_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhwi-stygian_zinogre_render_2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhwi-rajang_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhwi-viper_tobi-kadachi_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gthumbnails/mhwi-namielle_render_001.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/mhwi-zinogre_render_001.png"
]

var locationURL = [
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/monster-hunter-world-ancient-forest-location-information-300.jpg",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/coral_highlands_6.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/wildspire_5.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rotten_vale_2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/elder_recess_5.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/zorah-magdaros-large-monster-hunter-world-mhw.jpg",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/xenojiiva-monster-hunter-world-large-monster.jpg",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/everstream-header.jpg",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kulve_taroth-monster-hunter-world-large-monster.jpg",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/special_arena_2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/mhw-arena-entrance.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/hoarfrost-reach-location-icerborne-mhw-wiki-guide.jpg",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/guide-land-location-mhw-wiki-guide.jpg",
    "https://www.pcgamesn.com/wp-content/sites/pcgamesn/2020/03/SafiJiva.jpg"
] 

var setURL = [
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/leather_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/chainmail_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/hunters_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/bone_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/vespoid_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kestodon_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gajau_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/jagras_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kulu_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/alloy_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/pukei_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/barroth_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/jyura_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kadachi_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/high_metal_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/king_beetle_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/butterfly_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/shamos_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/hornetaur_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/anja_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rathian_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/tzitzi_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/lumu_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/girros_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/baan_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/ingot_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/death_stench_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/brigade_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/legiana_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/odogaron_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rathalos_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/diablos_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kirin_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/leather_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/leather_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/chainmail_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/chainmail_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/hunters_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/hunters_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/bone_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/bone_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/alloy_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/alloy_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/king_beetle_alpha_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/king_beetle_beta_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/butterfly_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/butterfly_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/vespoid_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/vespoid_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/hornetaur_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/hornetaur_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/mosswine_mask_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kestodon_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kestodon_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gajau_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gajau_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/shamos_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/shamos_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/jagras_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/jagras_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kulu_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kulu_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/tzitzi_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/tzitzi_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/girros_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/girros_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/pukei_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/pukei_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/barroth_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/barroth_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/anja_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/anja_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/jyura_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/jyura_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kadachi_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kadachi_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/lumu_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/lumu_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rathian_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rathian_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rath_heart_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rath_heart_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/baan_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/baan_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gastodon_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gastodon_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/barnos_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/barnos_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/dodogama_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/dodogama_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/zorah_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/zorah_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/high_metal_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/high_metal_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/ingot_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/ingot_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/brigade_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/brigade_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/faux_felyne_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/strategist_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/lavasioth_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/lavasioth_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/legiana_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/legiana_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/odogaron_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/odogaron_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rathalos_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rathalos_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rath_soul_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rath_soul_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/diablos_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/diablos_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/diablos_nero_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/diablos_nero_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/uragaan_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/uragaan_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/bazel_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/bazel_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/damascus_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/damascus_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/dober_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/dober_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/death_stench_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/death_stench_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/skull_mask_alpha_male.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/nergigante_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/nergigante_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/teostra_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/teostra_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kushala_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kushala_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/vaal_hazak_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/vaal_hazak_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kirin_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kirin_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/xenojiiva_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/xenojiiva_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/guild_cross_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/guild_cross_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/dragonking_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/commission_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/commission_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/deviljho_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/deviljho_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/sealed_eyepatch_alpha_female.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/shadow-shades-layered-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/blossom_armor_set_mhw_small.png",
    "",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/blossom_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kulu_ya_ku_head_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/wiggler_head_alpha.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kulve_taroth_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kulve_taroth_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kirin-gamma-armor-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/dante_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/lunastra-a-armor-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/lunastra-b-armor-set-mhw-wiki-guide.png",
    "",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/vaal-hazak-gamma-armor-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/drachen_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/azure_starlord_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kulve_taroth_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/lunastra-gamma-armor-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/xenojiiva_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/zorah-gamma-armor-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/nergigante_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kushala_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/teostra_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/bone-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/alloy-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/vespoid-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/hornetaur-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kestodon_alpha_plus_armor_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gajau_alpha_plus_armor_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/shamos_alpha_plus_armor_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gastodon_alpha_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/barnos_alpha_plus_armor_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/wulg_alpha_plus_armor_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/cortos_alpha_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/jagras-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/tzitzi-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/girros-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/dodogama-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kulu-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/pukei-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/coral-pukei-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/barroth-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/jyura-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/beo-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kadachi-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/viper-kadachi-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/high-mental-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/banbaro-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/anja-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/fulgur_anja_alpha_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rathian-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rath-heart-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/lumu-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/lumu-phantsm-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/baan-alpha+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/bone-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/alloy-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/vespoid-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/hornetaur-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kestodon_beta_plus_armor_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gajau_beta_plus_armor_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/shamos_beta_plus_armor_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/gastodon_beta_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/barnos_beta_plus_armor_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/wulg_beta_plus_armor_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/cortos_beta_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/jagras-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/tzitzi-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/girros-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/dodogama-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kulu-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/pukei-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/coral-pukei-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/barroth-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/jyura-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/beo-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kadachi-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/viper-kadachi-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/high-mental-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/banbaro-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/anja-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/fulgur_anja_beta_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rathian-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rath_heart_beta_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/lumu-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/lumu-phantsm-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/baan-beta+-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/artian_alpha_plus_armor_set_mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/artian-beta-plus-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/clockwork_alpha_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/clockwork_beta_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/ingot_alpha_plus_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/ingot_beta_plus_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/pearlspring-alpha-plus-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/guildwork-alpha-plus-set-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/guildwork-betaa-plus-set-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/ruiner-nergi-beta-plus-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/ruiner-nergi-alpha-plus-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/silver-sol-beta-plus-set-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/silver-sol-alpha-plus-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/golden-lune-beta-plus-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/golden-lune-alpha-plus-set-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/zinogre-beta-set-plus-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/zinogre-alpha-set-plus-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/yian-garuga-beta-set-plus-mhw-wiki-guide3.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/yian-garuga-alpha-set-plus-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/zorah-beta-plus-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/zorah-alpha-plus-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/shara-ishvalda-beta-plus-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/shara-ishvalda-alpha-plus-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/namielle-beta-plus-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/namielle-alpha-plus-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kirin-beta-plus-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kirin-alpha-plus-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kushala-beta-plus-armor-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kushala-alpha-plus-armor-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/teostra-beta-plus-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/teostra-alpha-plus-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/blackveil-hazak-beta-plus-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/blackveil-hazak-alpha-plus-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/velkhana_beta_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/velkhana_alpha_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/guild-palace-beta+-set-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/guild-palace-alpha+-set-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/savage-jho-beta-plus-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/savage-jho-alpha-plus-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/seething_bazel_beta_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/seething_bazel_alpha_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/damascus_beta_plus_set_mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/damascus_alpha_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/dober_beta_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/dober_alpha_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/black_belt_beta_plus_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/black_belt_alpha_plus_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/brute-tigrex-beta-plus-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/brute-tigrex-alpha-plus-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/brute-tigrex-beta-plus-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/brute-tigrex-alpha-plus-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/brachydios_beta_plus_armor_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/brachydios_alpha_plus_armor_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/acidic_glavenus_beta_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/acidic_glavenus_alpha_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rajang-beta-plus-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rajang-alpha-plus-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/glavenus_beta_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/glavenus_alpha_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/nargacuga_beta_plus_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/nargacuga_alpha_plus_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/uragaan_beta_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/uragaan_alpha_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/lavasioth_beta_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/lavasioth_alpha_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/death_garon_beta_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/death_garon_alpha_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/odogaron-beta-plus-set1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/odogaron-alpha-plus-set1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/shrieking_legia_beta_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/shrieking_legia_alpha_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/legiana_beta_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/legiana_alpha_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/diablos_nero_beta_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/diablos_nero_alpha_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/diablos_beta_plus_armor_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/diablos_alpha_plus_armor_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rath_soul_beta_armor_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rath_soul_alpha_armor_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rathalos_beta_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rathalos_alpha_plus_armor_set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/barioth-beta-plus-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/barioth-alpha-plus-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/lunastra-beta-set-plus-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/lunastra-alpha-set-plus-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/claire-alpha+armor-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/leon-alpha+armor-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/stygian-zin-alpha+set-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/stygian-zin-beta+set-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/safi'jiiva-alpha+set-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/safi'jiiva-beta+set-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/oolong-alpha+-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/dragonseal-earrings-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/origin-armor-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/pulverizing-feather-mhw-wiki-guide.png",
    "",
    "",
    "",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/divers_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/divers_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/harvest-armor-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/harvest-armor-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/orion-layered-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/orion-armor-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/aloy_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/aloy_alpha_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/ryu_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/ryu_armor_set_mhw_small.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/sakura-armor-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/geralt-armor-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/ciri-armor-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/showman-earrings-alpha+mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/showman-earrings-alpha+mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/astral-alpha-set-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/banuk_-alpha-plus-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/buff-body-alpha+-set-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/duffel-penguin-mask-alpha.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/sealed-dragon-cloth-alpha+.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/wyverian-ears-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/shield-weaver-armor-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/defender-alpha-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/guardian-armor_iceborne-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/furious-rajang-alpha-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/furious-rajang-beta-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/raging-brachy-alpha-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/raging-brachy-beta-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/rose-alpha-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kulve-taroth-a-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/kulve-taroth-b-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/namielle-gamma-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/alatreon-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/alatreon-beta-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/frostfang_barioth_alpha+mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/frostfang_barioth-beta-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/passionate_alpha+armor_set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/dragon-set-mhw-wiki-guide2.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/fatalis_beta+armor-set-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/demon_lord-set-mhw-wiki-guide1.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/velkhana_gamma-mhw-wiki-guide.png",
    "https://monsterhunterworld.wiki.fextralife.com/file/Monster-Hunter-World/azure_age_alpha-mhw-wiki-guide.png"
]

export  { 
        randOfTheDay, GetSortOrder, capitalizeFirstLetter,
        missingItem, missingArmorSet, missingWeapon, missingMonster, missingArmor, missingCharm, missingSkill,
        armorType, weaponType, weaponName,
        setURL, locationURL, monsterImgURL, monsterIconURL, defaultWeaponURL,
        elementName, elementIcon
        }